---
- name: Create list of InfluxDB data servers
  ansible.builtin.set_fact:
    influx_urls_list: >-
      {% set influx_urls_list = [] %}
      {% for influx_host in groups.influxdb_data %}
        {% set influx_url = 'http://'+influx_host+':'+influx_port %}
        {% set influx_urls_list = influx_urls_list.append(influx_url) %}
      {% endfor %}
      {{ influx_urls_list }}
  when:
    - influx_urls_list is not defined
    - groups.influxdb_data is defined

- name: Check influx_urls_list variable
  ansible.builtin.assert:
    that:
      - "influx_urls_list is defined"
      - "influx_urls_list|length > 0"

- name: "Check if Telegraf '{{ telegraf_version }}' exists on '{{ telegraf_base_url }}'"
  block:
    - name: "Check url '{{ telegraf_url }}'"
      ansible.builtin.uri:
        url: "{{ telegraf_url }}"
      register: http_response
    
    - name: "'{{ telegraf_url }}' HTTP response code == '200'"
      ansible.builtin.assert:
        that:
          - "http_response.status == 200"
        fail_msg: "'{{ telegraf_url }}' HTTP response code == '{{ http_response.status }}'"
  
  delegate_to: localhost
  run_once: true
  when:
    - "not local_install|default(false)|bool"
...
